input {
  jdbc {
    id => "UpdateCashCow_CashCowFlowDetail_input_jdbc"
    type => "UpdateCashCow_CashCowFlowDetail"
    jdbc_driver_library => "/opt/ysbapi/logstash/lib/mysql-connector-java-8.0.17.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://${SLAVE_DATABASE_URL}/db_biz_dc?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true"
    jdbc_user => "${SLAVE_DATABASE_USERNAME}"
    jdbc_password => "${SLAVE_DATABASE_PASSWORD}"
    jdbc_fetch_size => 5000
    statement => "
                select pid, id
                from (select a.id pid, cash_cow_withdraw_flow_id as id
                      from db_pay.ts_cash_cow_invoice_divide_detail a
                      where a.id >= :sql_last_value
                      order by a.id
                      limit 2000) v1
                union all
                select pid, id
                from (select id pid, divide_id as id
                      from db_pay.ts_cash_cow_invoice_divide_detail a
                      where a.id >= :sql_last_value
                      order by a.id
                      limit 2000) v2
                order by pid
    "

    #影响last_run_metadata_path 的时间戳
    jdbc_default_timezone =>"Asia/Shanghai"
    #记录最后一次运行的结果
    record_last_run => true
    #上面运行结果的保存位置
    last_run_metadata_path => "/opt/ysbapi/logstash/lastrun/UpdateCashCow_CashCowFlowDetail1.txt"
    use_column_value => true
    tracking_column => "pid"
    tracking_column_type => "numeric"
    # 每分钟补偿一次增量
    schedule => "*/31 * * * * *"
  }
}
filter {
  if [type] == "UpdateCashCow_CashCowFlowDetail" {
    jdbc_batch_streaming {
      jdbc_driver_library => "/opt/ysbapi/logstash/lib/mysql-connector-java-8.0.17.jar"
      jdbc_driver_class => "com.mysql.jdbc.Driver"
      jdbc_connection_string => "${JDBC_CONNECTION_STRING}"
      jdbc_user => "${SLAVE_DATABASE_USERNAME}"
      jdbc_password => "${SLAVE_DATABASE_PASSWORD}"
      db_init_threads => 1
      db_max_threads => 1
      size => 50
      merge_field => "id"
      statement_path => "/opt/ysbapi/logstash/config/pc_cash_cow_flow/pc_cash_cow_flow_by_id.sql"
    }
  }
  ruby {
    code => "event.to_hash.keys.each do |key|
      camel_case_key = key.gsub(/_([a-z0-9])/) { $1.upcase }
        if camel_case_key != key
          event.set(camel_case_key, event.get(key))
          event.remove(key)
        end
      end"
    }
}

output {

   elasticsearch {
      document_id => "%{id}"
      document_type => "_doc"
      index => "pc_cash_cow_flow"
      hosts => ["${ELASTIC_URL}"]
      user => "${ELASTIC_USER}"
      password => "${ELASTIC_PASSWORD}"
      manage_template =>  true
      template => "/opt/ysbapi/logstash/config/pc_cash_cow_flow/mapping.json"
      template_name => "pc_cash_cow_flow"
      template_overwrite => true
    }

}